version: '3.3'
services:
  gierre_db:
    container_name: 'mysql_gierre_db'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'gierre_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'gierre_app'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'gierre_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'gierre_root_password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db-gierre:/var/lib/mysql
# Names our volume
volumes:
  my-db-gierre: